import { ServiceCategory, ProProfile } from './types';
import { 
  Zap, Wind, Monitor, Bike, Car, Wrench, Shirt, Home, PaintBucket, 
  Utensils, CalendarCheck, Camera, Music, Dumbbell, BookOpen, Truck, Briefcase
} from 'lucide-react';

export const CATEGORY_ICONS: Record<ServiceCategory, any> = {
  [ServiceCategory.ELECTRICIAN]: Zap,
  [ServiceCategory.AC_REPAIR]: Wind,
  [ServiceCategory.COMPUTER]: Monitor,
  [ServiceCategory.BIKE]: Bike,
  [ServiceCategory.CAR]: Car,
  [ServiceCategory.PLUMBER]: Wrench,
  [ServiceCategory.WASHING_MACHINE]: Shirt,
  [ServiceCategory.HOME_DESIGNER]: Home,
  [ServiceCategory.DECORATOR]: PaintBucket,
  [ServiceCategory.CATERING]: Utensils,
  [ServiceCategory.PROGRAM_MANAGER]: CalendarCheck,
  [ServiceCategory.PHOTOGRAPHER]: Camera,
  [ServiceCategory.DANCER]: Music,
  [ServiceCategory.GYM_TRAINER]: Dumbbell,
  [ServiceCategory.TEACHER]: BookOpen,
  [ServiceCategory.TRANSPORTER]: Truck,
  [ServiceCategory.OTHER]: Briefcase,
};

export const CATEGORY_IMAGES: Record<ServiceCategory, string> = {
  [ServiceCategory.ELECTRICIAN]: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.AC_REPAIR]: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.COMPUTER]: "https://images.unsplash.com/photo-1597852074816-d933c7d2b988?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.BIKE]: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.CAR]: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.PLUMBER]: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.WASHING_MACHINE]: "https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.HOME_DESIGNER]: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.DECORATOR]: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.CATERING]: "https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.PROGRAM_MANAGER]: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.PHOTOGRAPHER]: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.DANCER]: "https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.GYM_TRAINER]: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.TEACHER]: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.TRANSPORTER]: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&w=200&q=80",
  [ServiceCategory.OTHER]: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=200&q=80",
};

export const INDIAN_CITIES = [
  "Mumbai, Maharashtra", "Delhi, Delhi", "Bangalore, Karnataka", "Hyderabad, Telangana", "Ahmedabad, Gujarat", 
  "Chennai, Tamil Nadu", "Kolkata, West Bengal", "Surat, Gujarat", "Pune, Maharashtra", "Jaipur, Rajasthan", 
  "Lucknow, Uttar Pradesh", "Kanpur, Uttar Pradesh", "Nagpur, Maharashtra", "Indore, Madhya Pradesh", "Thane, Maharashtra", 
  "Bhopal, Madhya Pradesh", "Visakhapatnam, Andhra Pradesh", "Pimpri-Chinchwad, Maharashtra", "Patna, Bihar", "Vadodara, Gujarat", 
  "Ghaziabad, Uttar Pradesh", "Ludhiana, Punjab", "Agra, Uttar Pradesh", "Nashik, Maharashtra", "Faridabad, Haryana", 
  "Meerut, Uttar Pradesh", "Rajkot, Gujarat", "Kalyan-Dombivli, Maharashtra", "Vasai-Virar, Maharashtra", "Varanasi, Uttar Pradesh", 
  "Srinagar, J&K", "Aurangabad, Maharashtra", "Dhanbad, Jharkhand", "Amritsar, Punjab", "Navi Mumbai, Maharashtra", 
  "Allahabad, Uttar Pradesh", "Howrah, West Bengal", "Ranchi, Jharkhand", "Gwalior, Madhya Pradesh", "Jabalpur, Madhya Pradesh", 
  "Coimbatore, Tamil Nadu", "Vijayawada, Andhra Pradesh", "Jodhpur, Rajasthan", "Madurai, Tamil Nadu", "Raipur, Chhattisgarh", 
  "Kota, Rajasthan", "Guwahati, Assam", "Chandigarh, Chandigarh", "Solapur, Maharashtra", "Hubballi-Dharwad, Karnataka", 
  "Bareilly, Uttar Pradesh", "Moradabad, Uttar Pradesh", "Mysore, Karnataka", "Gurgaon, Haryana", "Aligarh, Uttar Pradesh", 
  "Jalandhar, Punjab", "Tiruchirappalli, Tamil Nadu", "Bhubaneswar, Odisha", "Salem, Tamil Nadu", "Mira-Bhayandar, Maharashtra", 
  "Warangal, Telangana", "Thiruvananthapuram, Kerala", "Bhiwandi, Maharashtra", "Saharanpur, Uttar Pradesh", "Guntur, Andhra Pradesh", 
  "Amravati, Maharashtra", "Bikaner, Rajasthan", "Noida, Uttar Pradesh", "Jamshedpur, Jharkhand", "Bhilai, Chhattisgarh", 
  "Cuttack, Odisha", "Firozabad, Uttar Pradesh", "Kochi, Kerala", "Nellore, Andhra Pradesh", "Bhavnagar, Gujarat", 
  "Dehradun, Uttarakhand", "Durgapur, West Bengal", "Asansol, West Bengal", "Rourkela, Odisha", "Nanded, Maharashtra", 
  "Kolhapur, Maharashtra", "Ajmer, Rajasthan", "Akola, Maharashtra", "Gulbarga, Karnataka", "Jamnagar, Gujarat", 
  "Ujjain, Madhya Pradesh", "Loni, Uttar Pradesh", "Siliguri, West Bengal", "Jhansi, Uttar Pradesh", "Ulhasnagar, Maharashtra", 
  "Jammu, J&K", "Sangli-Miraj & Kupwad, Maharashtra", "Mangalore, Karnataka", "Erode, Tamil Nadu", "Belgaum, Karnataka", 
  "Ambattur, Tamil Nadu", "Tirunelveli, Tamil Nadu", "Malegaon, Maharashtra", "Gaya, Bihar", "Jalgaon, Maharashtra", 
  "Udaipur, Rajasthan", "Maheshtala, West Bengal"
].sort();

export const MOCK_PROS: ProProfile[] = [
  {
    id: 'p1',
    userId: 'u2',
    name: 'Robert Fox',
    category: ServiceCategory.ELECTRICIAN,
    description: 'Master electrician with 15 years experience in residential wiring and smart home setups.',
    hourlyRate: 45,
    rating: 4.9,
    reviewCount: 128,
    location: 'Mumbai, Maharashtra',
    imageUrl: 'https://picsum.photos/200/200?random=1',
    workPhotos: ['https://picsum.photos/400/300?random=101', 'https://picsum.photos/400/300?random=102'],
    isVerified: true,
    mobile: '+91 98765 43210',
    address: 'Shop 12, Main Market, Mumbai',
    idProof: {
      front: 'https://picsum.photos/300/200?random=201',
      back: 'https://picsum.photos/300/200?random=202'
    }
  },
  {
    id: 'p2',
    userId: 'u3',
    name: 'Jenny Wilson',
    category: ServiceCategory.HOME_DESIGNER,
    description: 'Modern interior designer focusing on minimalist and sustainable living spaces.',
    hourlyRate: 80,
    rating: 4.8,
    reviewCount: 95,
    location: 'Bangalore, Karnataka',
    imageUrl: 'https://picsum.photos/200/200?random=2',
    workPhotos: ['https://picsum.photos/400/300?random=103', 'https://picsum.photos/400/300?random=104'],
    isVerified: true,
    mobile: '+91 98765 43211',
    address: '45/B, Tech Park Road, Bangalore',
  },
  {
    id: 'p3',
    userId: 'u4',
    name: 'Albert Flores',
    category: ServiceCategory.PLUMBER,
    description: 'Emergency plumbing specialist. Leaks, pipes, and heater installations.',
    hourlyRate: 60,
    rating: 4.7,
    reviewCount: 210,
    location: 'Delhi, Delhi',
    imageUrl: 'https://picsum.photos/200/200?random=3',
    workPhotos: ['https://picsum.photos/400/300?random=105'],
    isVerified: false,
    mobile: '+91 98765 43212',
    address: 'Sector 4, Dwarka, Delhi',
  },
  {
    id: 'p4',
    userId: 'u5',
    name: 'Esther Howard',
    category: ServiceCategory.GYM_TRAINER,
    description: 'Certified personal trainer helping you achieve your fitness goals.',
    hourlyRate: 50,
    rating: 5.0,
    reviewCount: 42,
    location: 'Pune, Maharashtra',
    imageUrl: 'https://picsum.photos/200/200?random=4',
    workPhotos: ['https://picsum.photos/400/300?random=106'],
    isVerified: true,
    mobile: '+91 98765 43213',
    address: 'FitLife Gym, FC Road, Pune',
  },
  {
    id: 'p5',
    userId: 'u6',
    name: 'Guy Hawkins',
    category: ServiceCategory.CAR,
    description: 'Expert mechanic for all car brands. Mobile service available.',
    hourlyRate: 75,
    rating: 4.6,
    reviewCount: 88,
    location: 'Chennai, Tamil Nadu',
    imageUrl: 'https://picsum.photos/200/200?random=5',
    workPhotos: ['https://picsum.photos/400/300?random=107'],
    isVerified: true,
    mobile: '+91 98765 43214',
    address: 'AutoHub Garage, Anna Nagar, Chennai',
  }
];